---
name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run an Orbiter 1 instance in the background
        run: npm run start:orbiter1:background
      - name: Run an Orbiter 2 instance in the background
        run: npm run start:orbiter2:background
      - name: Run tests
        run: npm run test:ci
      - name: Run browser tests
        run: npm run test:browser
